### ISSUE TITLE
url structure question

### ISSUE THREAD

**Issue by beaucronin** [okdistribute/papertalk#14]
We currently have both reactions and articles as "top-level" urls:

```
/article/<article_id>
/reaction/<reaction_id>
```

but we could also imagine doing it thus:

```
/article/<article_id>/reaction/<reaction_id>
```

which would make more sense if reactions were always going to be linked to exactly one article.

But I don't think this is the case - for example in the future we may want to enable reactions that refer to _collections_ of articles.

Thoughts?

**Comment by okdistribute** [comment]
I think it's good for now to keep reactions separate as they are separate in the database as well. It does make sense to nest them, but it's an unnecessary complication as of right now. In the future we can always change it, though!

As for how article-reaction pairs should be referenced, consider MongoDB's suggested Manual References (http://docs.mongodb.org/manual/reference/database-references/#document-references), for example this schema:

```
article := {"_id" : ObjectID, "title": "Visualizing communication", 
"reactions": [ObjectID1, ObjectID2]}

reaction := {"_id" ObjectID, "title": "Visualizing communication needs work",  
article_id: ObjectID}
```

This way we can cross-reference and retrieve them with little headache

**Comment by okdistribute** [comment]
I think that `/article/<id>/reactions` would be a good one to have to return reaction results for a given article.. and then each links to `/reaction/<reaction_id>`

**Comment by beaucronin** [comment]
This seems reasonable, as long as there is a single place to find a given reaction.
