### ISSUE TITLE
Create reaction

### ISSUE THREAD

**Issue by okdistribute** [okdistribute/papertalk#2]
You should be able to create a reaction to a paper. This should be using markdown. These should be stored in our database. Let's use mongodb.

**Comment by beaucronin** [comment]
I'm working on this one, under the reaction branch. PR forthcoming.

**Comment by beaucronin** [comment]
OK, this is ready to get merged, but I don't know how to add PageDown to the dependency manager so that it ends up in the vendor directory.

**Comment by okdistribute** [comment]
It looks like we can create a reaction. Next steps include getting to the reaction page via the article page, and when saving, updating that reaction-article pair.

**Comment by okdistribute** [comment]
Cool so now we've got a lot of basic functionality going with this -- I merged in all of our changes and created the ability for us to write tests today. Next it should be straightforward to be able to write a reaction on an article's page
