### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by okdistribute** [okdistribute/papertalk#29]
Transfer to SSL on heroku. Costs $20/mo

**Comment by beaucronin** [comment]
What account/creds do I need to do this?

And are there other things we should add to the account?

**Comment by okdistribute** [comment]
We'll probably want to pay for another dyno and some extra mongodb space, as well.

I added you as an admin on heroku, let me know if that's enough. I might need to promote you or something but I don't have time to look right now

**Comment by beaucronin** [comment]
"You do not have permission to provision paid resources for papertalk. Only the app owner, krmckelv@gmail.com, can do that."

So...we'll have to figure out a way to pay for it. Can you try adding, and see how it asks for payment? We could just add my credit card to the account or something.

**Comment by beaucronin** [comment]
Done - SSL endpoint enabled and cert added. We show up green in the address bar!

We should figure out where we want to store the secret bits.
