### ISSUE TITLE
Reactions user interface

### ISSUE THREAD

**Issue by okdistribute** [okdistribute/papertalk#31]
The user interface on reactions is lacking. Maybe grabbing a designer could be nice.

**Comment by beaucronin** [comment]
Taking a pass at this now. I'm going to try putting the reaction authoring/preview into tabs. Might also play around with letting the user add tags or categories to the reaction.

**Comment by okdistribute** [comment]
Okay great, this sounds nice. It might be nice to put reaction authoring directly in the article page, instead of opening a new page just expanding some div, perhaps.

**Comment by beaucronin** [comment]
yeah, that could be cool. I'll take a look.

On Mon, Nov 11, 2013 at 10:51 PM, Karissa McKelvey <notifications@github.com

**Comment by okdistribute** [comment]
Check out the new article page. I have an idea --

Below the article title author and year, there is a <hr>

Below that, put tab headers -> New Reaction, Reaction

New Reaction is default view if there are 0 reactions, reactions otherwise.

**Comment by beaucronin** [comment]
Is this deployed to heroku?

**Comment by beaucronin** [comment]
Also, I have a PR on a branch that I think improves the basic reaction authoring page.

**Comment by beaucronin** [comment]
I'm honored you would consider this closed...

**Comment by okdistribute** [comment]
Haha. User interfaces are never closed..
