### ISSUE TITLE
Create article from pdf

### ISSUE THREAD

**Issue by okdistribute** [okdistribute/papertalk#34]
you should be able to copy + paste url from PDF and create an article by entering the title, author, year manually

**Comment by okdistribute** [comment]
A good user interaction for this is enter a pdf link into the search box -> article/search redirects to article/pdf that has boxes for authors, title, year -> inserts into db and takes you to article page

**Comment by okdistribute** [comment]
@beaucronin Check out https://github.com/karissamck/papertalk/pull/36 for a blueprint on how the form should be created

**Comment by beaucronin** [comment]
Are we sure we want to include this in the MVP? Manual entry of paper metadata seems to open a whole can of worms. Are we sure we need this at all?

Not just being lazy, I swear!

**Comment by okdistribute** [comment]
I think it's okay, since we already allow them to enter in reactions. They'll have to be signed up for Google in order to do it, so we won't get spam.

**Comment by okdistribute** [comment]
Checkitout! https://github.com/karissamck/papertalk/commit/11a5fc37e1b0f81dc854bde4238bd67314c8f21c
