### ISSUE TITLE
mongo backups

### ISSUE THREAD

**Issue by beaucronin** [okdistribute/papertalk#39]
I think we should at least have a basic DR capability before we open the beta. Could this be as simple as enabling scheduled (nightly) backups from MongoLab to S3? 

https://devcenter.heroku.com/articles/mongolab#taking-backups

**Comment by okdistribute** [comment]
great idea

**Comment by okdistribute** [comment]
This is 15$/mo for daily backups

**Comment by beaucronin** [comment]
OK, great - I say we go ahead with this.

I think this means we need to set up an S3 bucket to be the target. I can
look into getting that set up.

On Mon, Nov 11, 2013 at 10:49 PM, Karissa McKelvey <notifications@github.com

**Comment by okdistribute** [comment]
No, actually mongolab can handle all of this for us! No stress

**Comment by beaucronin** [comment]
oh, cool.

**Comment by okdistribute** [comment]
Backups are scheduled now for every day at 6am. They hold the last 8 backups.
