### ISSUE TITLE
easy bug reporting

### ISSUE THREAD

**Issue by beaucronin** [okdistribute/papertalk#40]
We should have a very easy way to report bugs and other issues in context. Could be as simple as a mailto: link, or a popover link from one of the in-context support providers.

**Comment by okdistribute** [comment]
This is good. Also, if the server encounters any 500 errors, it should send an email or something

**Comment by okdistribute** [comment]
I think flask might have a built-in way to do this. http://flask.pocoo.org/docs/errorhandling/

**Comment by beaucronin** [comment]
OK, I'm working on this now. I'm going to try:
- [Barometer](http://getbarometer.com/) for voluntary feedback
- the builtin flask error emails for automatic error reporting

**Comment by okdistribute** [comment]
Check out this: https://www.getsentry.com/welcome/

**Comment by beaucronin** [comment]
Sweet - I'll check it out.

**Comment by beaucronin** [comment]
OK, added sentry and merged 77ba820
