### ISSUE TITLE
Cache mendeley responses

### ISSUE THREAD

**Issue by okdistribute** [okdistribute/papertalk#59]
We should cache searches from mendeley. Not sure how this should be done quite yet

**Comment by beaucronin** [comment]
As it is, we're adding all Mendeley search results to the db. Is this
enough? What else could we do?

**Comment by okdistribute** [comment]
We add all mendeley search results to the db, but we still make that query to mendeley every time the search button is pressed.

**Comment by beaucronin** [comment]
How frequent are exactly-repeated queries though?

**Comment by okdistribute** [comment]
Something better might be caching the search queries. We then only query mendeley if that same search hasn't been done in the past day

**Comment by okdistribute** [comment]
Probably not that frequent.

**Comment by beaucronin** [comment]
Yeah, my (uninformed) guess is that cache hits would be infrequent.

**Comment by okdistribute** [comment]
Maybe then we say we won't fix this.
